# -*- coding: utf-8 -*-
"""project_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o3yde4B8BOX_5GFYDyM8lh5W_ySCbWtC

Data Description:

The London Air Quality Network (LAQN) is run by the Environmental Research Group of King’s College London. The network collects air pollution data from London boroughs, with each one funding monitoring in its own area.

The dataset has the information for 6 different Air Pollution measures:
- NO - Nitric Oxide (ug/m3)
- NO2 - Nitrogen Dioxide (ug/m3)
- NOX - Oxides of Nitrogen (ug/m3 as NO2)
- PM10 - PM10 Particulate (by TEOM) (ug/m3)
- FINE - PM2.5 (not reference equiv.) (by TEOM) (ug/m3)
- WDIR - Wind Direction (oN)
"""

from google.colab import drive
drive.mount('/content/drive')

"""**Gat Data :  **"""

datapath = '/content/drive/My Drive/project-1/LondonAirQuality.csv'

import numpy as np

import pandas as pd
df = pd.read_csv(datapath)

df['Value']

df['Date'] = pd.to_datetime(df['ReadingDateTime']).dt.date
df['Time'] = pd.to_datetime(df['ReadingDateTime']).dt.time

"""**Shape of Dataset**"""

print(df.shape)

"""**20 First Data**"""

print(df.head(20))

"""**20 Last Data**"""

print(df.head(-20))

"""**How to mark invalid/ corrupt values as missing**"""

missing_value_formats = ["n.a.","?","NA","n/a", "na", "--"]
df = pd.read_csv("/content/drive/My Drive/project-1/LondonAirQuality.csv", na_values = missing_value_formats)

print(df)

"""**Remove rows with missing values**"""

newdf = df.dropna(axis=0)
newdf.shape

"""**Fill missing value with 0**"""

newdf = df.copy(deep=True)
newdf['Value'].fillna(0,inplace=True)
print(newdf['Value'].head(10))

"""**Fill missing value from the next row**"""

newdf = df.copy(deep=True)
newdf['Value'].fillna(method='bfill',inplace=True)
print(newdf['Value'].head(10))

"""**Fill missing value from the Before row**"""

newdf = df.copy(deep=True)
newdf['Value'].fillna(method='pad',inplace=True)
print(newdf['Value'].head(10))

"""*** Fill missing value with Avrage : ***

***with median***
"""

newdf = df.copy(deep=True)
newdf['Value'].fillna(newdf['Value'].median(),inplace=True)
print(newdf['Value'].head(10))

"""***with mean***"""

newdf = df.copy(deep=True)
newdf['Value'].fillna(newdf['Value'].mean(),inplace=True)
print(newdf['Value'].head(10))

"""**Information from Data**"""

df.Site.unique()

df.Species.unique()

df.Units.unique()

"""**Their number is the same :**"""

no = df.loc[df.Species=='NO']

no.describe()

no2 = df.loc[df.Species=='NO2']

no2.describe()

nox = df.loc[df.Species=='NOX']

nox.describe()

pm10 = df.loc[df.Species=='PM10']

pm10.describe()

fine = df.loc[df.Species=='FINE']

fine.describe()

wdir = df.loc[df.Species=='WDIR']

wdir.describe()

"""**Mean of different Species**"""

df.loc[df.Species=='NO'].mean()

df.loc[df.Species=='NO2'].mean()

df.loc[df.Species=='NOX'].mean()

df.loc[df.Species=='PM10'].mean()

df.loc[df.Species=='FINE'].mean()

df.loc[df.Species=='WDIR'].mean()

"""**Plot a Histogram Plot in Matplotlib**"""

import matplotlib.pyplot as plt

plt.hist(df['Value'])

plt.show()

import numpy as np

data = df['Value']

plt.hist(data, bins = np.arange(min(data), max(data) + 1, 1))

plt.show()

plt.hist(data, bins = 20)

plt.show()

"""The purpose of this project is to demonstrate your ability to work with, and clean a data set, and explore the data features.

The goal is to prepare tidy data that can be used for later analysis, and also underestand the pattern of each feature - such as daily or hourly pattern of different Air pollution measures, whether they are correlated, ...

You will be required to submit:
1) a tidy data set as described below,
2) a link to a Colab Notebook with your code for performing the analysis, with 3) full description of the variables, the data, and any transformations or work that you performed to clean up the data, and analyse and explore the data.
"""